sudo: false
language: node_js

cache:
  directories:
    - node_modules

branches:
  only:
    - master

notifications:
  email:
    on_failure: change

node_js:
  - '5.11'

before_install:
  - export CHROME_BIN=chromium-browser
  - npm i -g npm@^3.0.0
  - npm install

before_script:
  - npm prune
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run build.prod
  - npm run test
